version: 2.1

# https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
executors:
    dw-executor:
        working_directory: ~/repo
        docker:
            - image: sto3psl/dw-ci:1.4.0

# https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands
commands:
    restore_npm_cache:
        description: Restores .npm directory for faster installs
        steps:
            - restore_cache:
                  keys:
                      - v4-install-cache-{{ checksum "package-lock.json" }}
                      - v4-install-cache

jobs:
    test:
        executor: dw-executor
        steps:
            - checkout
            - restore_npm_cache

            - run:
                    environment:
                        HUSKY_SKIP_INSTALL: 1
                    command: npm ci

            - run:
                    name: Lint code
                    command: npm run lint
            - run:
                    name: Run tests
                    command: |
                        mkdir -p ~/reports/ava
                        npm test -- --tap | npx tap-xunit > ~/reports/ava/results.xml

            - save_cache:
                    key: v4-install-cache-{{ checksum "package-lock.json" }}
                    paths:
                        - ~/.npm

    publish:
        executor: dw-executor
        steps:
            - checkout

            - run:
                    name: Authenticate with registry
                    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run:
                    name: Publish Package
                    command: npm publish

workflows:
    test and publish:
        jobs:
            - test:
                  filters:
                      tags:
                          only: /^v.*/

            - publish:
                  context: Deployment Keys
                  requires:
                      - test
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
